### ISSUE TITLE
Missing Props in ZoomableImage Component Usage in lesson 18

### ISSUE THREAD

**Issue by astrxnomo** [codedex-io/react-101#8]
## Issue

The `ZoomableImage` component is used in `App.js` without the required props `imageURL` and `zoomFactor`.

## Expected

The `ZoomableImage` component should be used with the required props `imageURL` and `zoomFactor` to make it work properly.

## Solution

Update the usage of `ZoomableImage` in `App.js` to include the required props. For example:

```jsx
<ZoomableImage imageURL="https://i.imgur.com/ZIBbN09.jpeg" zoomFactor={10} />
```
## Code reference
https://github.com/codedex-io/react-101/blob/75398d5176e8783f39f92e32d196d852c87da72e/4-events/18-a-focus-in-art/App.js#L7C3-L7C38

**Comment by Dusch4593** [comment]
Hi @astrxnomo! 👋🏻 

Great catch! I updated the solution with your suggestion in https://github.com/codedex-io/react-101/commit/a10e1f479ba42de8f131d03947ee88fc145450c9.

I also updated the instructions for exercise 18 to explicitly ask for the `imageURL` and `zoomFactor` props to be added to `<ZoomableImage>` in the **App.js** file.

Thank you so much! 🙏🏻
